"""empty message

Revision ID: 5a13b592b0e1
Revises: 1a2b40f4091a
Create Date: 2018-09-12 12:20:37.777144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a13b592b0e1'
down_revision = '1a2b40f4091a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_token_model')
    # ### end Alembic commands ###
